### ISSUE TITLE
Failing to build APK after updating to 7.5.0

### ISSUE THREAD

**Issue by Adrianogba** [talsec/Free-RASP-Flutter#201]
**Describe the bug**
After upgrading freeRASP to version 7.5.0, the Android build fails due to an unresolved reference to `ScreenProtector` in the native Kotlin code. It seems that a required dependency is missing or not properly included.

---

**To Reproduce**

1. Create or use an existing Flutter project
2. Add freeRASP version 7.5.0 to `pubspec.yaml`
3. Run `flutter pub get`
4. Build the Android project (`flutter build apk` or run via Android Studio)

---

**Error output**

```
Got dependencies in `PROJECT_PATH`!
20 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
e: file:///DEPENDENCIES_PATH/hosted/pub.dev/freerasp-7.5.0/android/src/main/kotlin/com/aheaditec/freerasp/handlers/TalsecThreatHandler.kt:6:31 Unresolved reference 'ScreenProtector'.
e: file:///DEPENDENCIES_PATH/hosted/pub.dev/freerasp-7.5.0/android/src/main/kotlin/com/aheaditec/freerasp/handlers/TalsecThreatHandler.kt:29:13 Unresolved reference 'ScreenProtector'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':freerasp:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 52s
Running Gradle task 'assembleRelease'...                           53,1s
Gradle task assembleRelease failed with exit code 1
```

---

**Expected behavior**
The project should build successfully without requiring any additional manual dependency configuration in the Android module.

---

**Actual behavior**
The build fails due to missing `ScreenProtector` class reference in the plugin's native Android code.

---

**Workaround**
Downgrading to version 7.4.0 resolves the issue.

---

**Screenshots**
Not applicable

---

**Please complete the following information:**

* Device: Not device-specific (build-time issue)
* OS version: Windows 11
* Flutter version: 3.41.5
* freeRASP version: 7.5.0

---

**Additional context**
It appears that the `ScreenProtector` class might belong to a dependency that is not being transitively included anymore (possibly from Talsec SDK).

Manually adding a dependency such as:

```
implementation 'com.aheaditec.talsec.security:security-android:<version>'
```

might resolve the issue, according to chatgpt, still didn't tested yet, but this should not be required, right?

**Comment by Adrianogba** [comment]
@yardexx Its a brand new project, I just had updated from 7.4.0 to 7.5.0.
I've done a clean build, with flutter clean and also deleting the temporary files manually, even pub-cache.
Also got the same error building on a windows machine and a macbook with the same project.


```
android {
    namespace = "io.adrianogba.myapp"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

```


Even now after updating to 7.5.1:

C:\APP_PATH>flutter build apk
Downloading android-arm-profile/windows-x64 tools...             1.157ms
Downloading android-arm-release/windows-x64 tools...               383ms
Downloading android-arm64-profile/windows-x64 tools...             364ms
Downloading android-arm64-release/windows-x64 tools...             294ms
Downloading android-x64-profile/windows-x64 tools...               358ms
Downloading android-x64-release/windows-x64 tools...               307ms
Resolving dependencies in `C:\APP_PATH`...
Downloading packages...
  _fe_analyzer_shared 92.0.0 (98.0.0 available)
  analyzer 9.0.0 (12.0.0 available)
  analyzer_buffer 0.3.0 (0.3.1 available)
  auto_route_generator 10.4.0 (10.5.0 available)
  dart_style 3.1.3 (3.1.8 available)
  json_serializable 6.13.0 (6.13.1 available)
  lean_builder 0.1.6 (0.1.7 available)
  meta 1.17.0 (1.18.2 available)
  test 1.30.0 (1.31.0 available)
  test_api 0.7.10 (0.7.11 available)
  test_core 0.6.16 (0.6.17 available)
  vector_math 2.2.0 (2.3.0 available)
  watcher 1.1.4 (1.2.1 available)
  win32 5.15.0 (6.0.0 available)
Got dependencies in `C:\APP_PATH`!
14 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
e: file:///C:/USER_PATH/AppData/Local/Pub/Cache/hosted/pub.dev/freerasp-7.5.1/android/src/main/kotlin/com/aheaditec/freerasp/handlers/TalsecThreatHandler.kt:6:31 Unresolved reference 'ScreenProtector'.
e: file:///C:/USER_PATH/AppData/Local/Pub/Cache/hosted/pub.dev/freerasp-7.5.1/android/src/main/kotlin/com/aheaditec/freerasp/handlers/TalsecThreatHandler.kt:29:13 Unresolved reference 'ScreenProtector'.
Font asset "feather.ttf" was tree-shaken, reducing it from 80488 to 8896 bytes (88.9% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 1872 bytes (99.9% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':freerasp:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights from a Build Scan (powered by Develocity).
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 33s
Running Gradle task 'assembleRelease'...                           94,5s
Gradle task assembleRelease failed with exit code 1

**Comment by Adrianogba** [comment]
One thing that might be relevant, it is signing release with debug key, I haven't created a jks for release yet.

**Comment by martinzigrai** [comment]
Hi @Adrianogba,

This should be resolved in **v8.0.0**. Please upgrade to this version and if the issue persists, do not hesitate to reopen this ticket.

Best regards,
Martin from Talsec team
